export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCESS="ALL_PRODUCT_SUCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const CLEAR_ERROR="CLEAR_ERROR";
export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCESS="PRODUCT_DETAILS_SUCESS";
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL";
